name: bopt
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.16
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - cvxpy==1.3.1
      - cython==0.29.34
      - ecos==2.0.12
      - joblib==1.2.0
      - numpy==1.24.3
      - osqp==0.6.2.post9
      - pydl8-5==0.1.8
      - qdldl==0.1.7
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - scs==3.2.3
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
