name: bopt
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2023.01.10
  - intel-openmp=2023.1.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - pandas=1.5.3
  - pip=23.0.1
  - prettytable=3.5.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - setuptools=66.0.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023c
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - cvxpy==1.3.1
      - cython==0.29.34
      - ecos==2.0.12
      - joblib==1.2.0
      - osqp==0.6.2.post9
      - pydl8-5==0.1.8
      - qdldl==0.1.7
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - scs==3.2.3
      - threadpoolctl==3.1.0