dist: trusty
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: PYTHON_VERSION="3.5" NUMPY_VERSION="1.13.1" SKLEARN_VERSION="0.21.0" SETUPTOOLS_VERSION="38.5.1"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python pip
  - source activate testenv
  - conda install --yes numpy setuptools scikit-learn cython nose pytest pytest-cov
  - pip install codecov
  - pip install .

script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=dl85 --pyargs dl85

after_success:
  - codecov
