dist: trusty
sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - env: PYTHON_VERSION="3.5" NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="nightly"
  # - env: PYTHON_VERSION="3.6" NUMPY_VERSION="1.14.2" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="0.21.3"
install:
- deactivate
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- MINICONDA_PATH=/home/travis/miniconda
- chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
- export PATH=$MINICONDA_PATH/bin:$PATH
- conda update --yes conda
- conda create -n testenv --yes python=$PYTHON_VERSION pip
- source activate testenv
- |
  if [ $SKLEARN_VERSION = "nightly" ]; then
      conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION setuptools cython nose pytest pytest-cov
      # install nightly wheels
      pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
  else
      conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION setuptools cython nose pytest pytest-cov
  fi
- pip install codecov
- pip install .
script:
- pytest -v --cov=dl85 --pyargs dl85 -s
after_success:
- codecov
- conda deactivate
deploy:
  provider: pypi
  edge: true # v2
  user: __token__
  password:
    secure: a7BQN7o+148QnZyFOAVMM1BiZ/p0/tj0ssxBH7UwVWihrOLkzIfD9zDF0Pt+WbhJwba3Prj3jybO1bzyxslbOSkoUdunce2flPobE3oGeja8JU5pzxEfIRbOCMOlmyg2G72USAwDKWnEdpyA0J9CfQms+cFHBWlHa2PhBFHvroFKw6GepkHDcBCuwZEVKxZdA+JThUYhGe+hOlLmFPKWb7FHpxoaWUpKEKx9F+gFGualIX/PmMh4vS1JWcYMu033XzGQ60ms0LFhHqNRX9uFVSMbWz9l4yfoOFGYiw2LZMbR/Po9dkKK1vdXamdoxcetVBmsUKXE1cz3Ybbfo57Yy3V1RNy03p9uQqA5ZM3MsdH0saW1BfUz4Yy9sBCZZWINZ09y1NB3bHB8w3D38HQz6sr0amrKlFtM5kRjq/GzN8MgPYC4i3yWzaiyMJTaamhQUNjMOD7oD9baDilmvndavK/1QCy/A4RswoiyH/EC0u5xBj+WFbM//uTCTqAmvEDq326Jcs5gFEnZRmJ0AnzNdacenGEi4xI8p1/K7YmYemFpTIocPGy8JQK9JdtWmm5wfOurxq350wl3Yck0N2KxHnC2Iz15kwnux33fGYgprRA7S6vOg43RlTpKrIoaLR+2Hl35PEHmRfbf+WSjqeKoBS2kBVNS2/rwnjDSHU54mB4=
  on:
    # tags: true
    branch: master
  distributions: sdist bdist_wheel
  allow_failure: true # v2
  skip_existing: true
  # skip_cleanup: true # v1
