build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "1.13.1"
      SCIPY_VERSION: "0.19.1"
      SKLEARN_VERSION: "*"
      TOXENV: py35

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  # install the dependencies
  - "conda install --yes pip numpy==%NUMPY_VERSION% scipy==%SCIPY_VERSION% scikit-learn==%SKLEARN_VERSION% setuptools cython nose pytest pytest-cov"
  - pip install tox
  - pip install codecov
  - pip install .

test_script:
#  - mkdir for_test
#  - cd for_test
  - tox
#  - pytest -v --cov=dl85 --pyargs dl85

after_test:
  - cp .coverage %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - codecov
