version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            pip install -r ../requirements.txt
            pip install .
