version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            pipenv shell
            pip install --user -r requirements.txt
            pip install .

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3
